document.write('<footer class="footer">');
document.write('    <div class="container">');
document.write('        <div class="footer_wrap">');
document.write('            <div class="footer_col">');
document.write('                <div class="footer-logo">');
document.write('                    <img src="./frontend/img/main-logo-white.svg" alt="">');
document.write('                </div>');
document.write('                <div class="office_info">');
document.write('                    <p>');
document.write('                        Our aim is to exceed expectations through high standards, reliability and');
document.write('                        passion for delivering an outstanding experience. With over 12 years of staffing solution');
document.write('                        experience.');
document.write('                    </p>');
document.write('                </div>');
document.write('                <div class="useful_link_bottom mt-5">');
document.write('                    <h4 class="text-white mb-3">Lets Get Connected</h4>');
document.write('                    <div class="partner_wrap">');
document.write('                        <img src="./frontend/img/facebook-color.svg" alt="">');
document.write('                        <img src="./frontend/img/linkedin-green.svg" alt="">');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="footer_col">');
document.write('                <div class="useful_inner">');
document.write('                    <div class="useful_link-inner">');
document.write('                        <h4 class="text-white">Usefull Links</h4>');
document.write('                        <div class="useful_points">');
document.write('                            <div>');
document.write('                                <p><a href="#">Home</a></p>');
document.write('                                <p><a href="#">About</a></p>');
document.write('                                <p><a href="#">Teams</a></p>');
document.write('                                <p><a href="#">Services</a></p>');
document.write('                                <p><a href="#">Projects</a></p>');
document.write('                                <p><a href="#">Reviews</a></p>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="footer_col">');
document.write('                <div class="contact_inner">');
document.write('                    <h4 class="text-white">Contact</h4>');
document.write('                    <div>');
document.write('                        <p>');
document.write('                            <img src="./frontend/img/call-green.svg" alt="">');
document.write('                            <a href="tel:0207 474 8888">0207 4748888</a>');
document.write('                        </p>');
document.write('                        <p>');
document.write('                            <img src="./frontend/img/mail-green.svg" alt="">');
document.write('                            <a href="mailto:info@docksidepersonnel.com">info@docksidepersonnel.com</a>');
document.write('                        </p>');
document.write('                        <p><img src="./frontend/img/location-green.svg" alt=""><a href="#">Unit F19 Expressway <br>');
document.write('                                London E16 1AH</a></p>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</footer>');

