document.write('<header class="header" id="header">');
document.write('    <nav class="navbar container-fluid">');
document.write('        <div class="burger" id="burger">');
document.write('            <span class="burger-line"></span>');
document.write('            <span class="burger-line"></span>');
document.write('            <span class="burger-line"></span>');
document.write('        </div>');
document.write('        <a href="./index.html" class="brand">');
document.write('            <img src="./frontend/img/magestic-soft-logo.svg" class="obj_fit_contain" alt="">');
document.write('        </a>');
document.write('        <div class="menu" id="menu">');
document.write('            <ul class="menu-inner">');
document.write('                <li class="menu-item"><a href="./index.html" class="menu_item active">Home</a></li>    ');
document.write('                <li class="menu-item drop_down">');
document.write('                    <a class="dropdown-toggle menu_item">Services</a>');
document.write('                    <ul class="dropdown_menu">');
document.write('                        <li><a href="./services-detail.html">Web Development</a></li>');
document.write('                        <li><a href="./services-detail.html">App Development</a></li>');
document.write('                        <li><a href="./services-detail.html">UI/UX Designing</a></li>');
document.write('                        <li><a href="./services-detail.html">Digital Marketing</a></li>');
document.write('                        <li><a href="./services-detail.html">Website Seo</a></li>');
document.write('                        <li><a href="./services-detail.html">Socail Media Management</a></li>');
document.write('                    </ul>');
document.write('                </li>');
document.write('                <li class="menu-item"><a href="./about.html" class="menu_item">About Us</a>');
document.write('                </li>');
document.write('                <li class="menu-item"><a href="./contact-us.html" class="menu_item">Contact Us</a></li>');
document.write('            </ul>');
document.write('        </div>');
document.write('        <div class="header-action">');
document.write('            <a href="" class="btn btn-outline ms-auto">Get Free Demo</a>');
document.write('        </div>');
document.write('    </nav>');
document.write('</header>');